# local kind cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # extraPortMappings:
  # # gatus
  # - containerPort: 30950
  #   hostPort: 8080
  # # httpbin
  # - containerPort: 30951
  #   hostPort: 8081
